;this file for FamiTone5.1 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


soundtrack_music_data:
	.byte 3
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,368,307 ; RPGBattleTheme - Ted Kerr
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,368,307 ; victoryloop - Ted Kerr
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; Cave - Ted Kerr

@instruments:
	.word @env1,@env0,@env0,@env1
	.word @env1,@env0,@env0,@env1
	.word @env2,@env0,@env0,@env1
	.word @env3,@env0,@env0,@env16
	.word @env4,@env0,@env0,@env1
	.word @env5,@env0,@env0,@env17
	.word @env6,@env0,@env0,@env0
	.word @env7,@env0,@env0,@env18
	.word @env8,@env0,@env0,@env1
	.word @env9,@env0,@env0,@env1
	.word @env10,@env0,@env0,@env18
	.word @env2,@env0,@env0,@env1
	.word @env11,@env0,@env0,@env1
	.word @env12,@env0,@env0,@env1
	.word @env13,@env0,@env0,@env0
	.word @env14,@env0,@env0,@env18
	.word @env15,@env0,@env0,@env1

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cc,$c9,$c8,$c5,$c4,$c2,$c1,$c0,$05,$c0,$00,$09
@env2:
	.byte $cc,$ca,$c8,$c6,$c4,$c2,$c0,$c0,$00,$07
@env3:
	.byte $cf,$cb,$04,$ca,$02,$c8,$02,$c7,$02,$c7,$00,$09
@env4:
	.byte $ce,$02,$cd,$02,$cc,$02,$cb,$ca,$ca,$c9,$c8,$c8,$c7,$c5,$00,$0d
@env5:
	.byte $ce,$ce,$cd,$cd,$cc,$cb,$ca,$ca,$c9,$03,$c8,$03,$c7,$02,$c7,$00
	.byte $0e
@env6:
	.byte $ce,$cd,$cc,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c1,$c0,$03,$c0,$00
	.byte $0e
@env7:
	.byte $cf,$cc,$cb,$ca,$c9,$c9,$c8,$05,$c7,$02,$c7,$00,$0a
@env8:
	.byte $cc,$1d,$cc,$00,$02
@env9:
	.byte $ce,$ce,$cd,$cd,$cc,$02,$cb,$cb,$ca,$ca,$c9,$c8,$c8,$c7,$02,$c6
	.byte $02,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$00,$19
@env10:
	.byte $ce,$cd,$cd,$cc,$06,$cc,$00,$05
@env11:
	.byte $ce,$02,$cd,$cd,$cc,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c6,$c5,$c5,$c4
	.byte $00,$0f
@env12:
	.byte $cc,$05,$c0,$06,$c0,$00,$00
@env13:
	.byte $c9,$c8,$c7,$c6,$c5,$c4,$c3,$c1,$c0,$06,$c0,$00,$0a
@env14:
	.byte $cf,$cc,$cb,$c9,$c8,$c6,$c5,$c4,$c3,$c2,$c0,$04,$c0,$00,$0c
@env15:
	.byte $ce,$02,$cd,$cd,$cb,$c9,$c8,$08,$c8,$00,$08
@env16:
	.byte $c2,$c0,$00,$01
@env17:
	.byte $c1,$00,$00
@env18:
	.byte $c2,$00,$00


; RPGBattleTheme - Ted Kerr
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $7c,$60,$8a,$1c,$83,$1e,$83,$1f,$85,$1e,$81,$1c,$81,$19,$81,$17
	.byte $83,$19,$83,$1a,$85,$19,$81,$17,$81,$14,$81
@ref1:
	.byte $12,$83,$14,$83,$15,$81,$1e,$85,$62,$87,$77,$21,$22,$78,$23,$24
	.byte $79,$23,$22,$7a,$21,$20,$77,$88,$1e,$1f,$78,$20,$21,$79,$20,$1f
	.byte $7a,$1e,$1d
@ref2:
	.byte $7c,$60,$8a,$1c,$83,$1e,$83,$1f,$85,$1e,$81,$1c,$81,$19,$81,$17
	.byte $83,$19,$83,$1a,$81,$6e,$f9,$87,$20,$85
@ref3:
	.byte $12,$83,$14,$83,$15,$81,$1e,$85,$61,$87,$77,$21,$22,$78,$23,$24
	.byte $79,$22,$21,$7a,$20,$1e,$77,$88,$1f,$20,$78,$21,$20,$79,$1f,$1e
	.byte $7a,$1d,$1c
@ref4:
	.byte $7c,$60,$1c,$83,$1a,$83,$23,$91,$1e,$8d,$1c,$85,$1a,$85
@ref5:
	.byte $18,$83,$1a,$83,$1c,$91,$1e,$9d
@ref6:
	.byte $7c,$1f,$83,$1d,$83,$1f,$89,$21,$85,$22,$83,$20,$83,$22,$85,$23
	.byte $89
@ref7:
	.byte $62,$22,$85,$76,$60,$8a,$22,$20,$22,$24,$25,$24,$25,$27,$29,$27
	.byte $29,$2a,$7c,$88,$20,$85,$23,$81,$62,$83,$22,$85,$8a,$20,$1f,$1e
	.byte $1d
@ref8:
	.byte $7c,$60,$1c,$83,$1e,$83,$1f,$85,$1e,$81,$1c,$81,$19,$81,$17,$83
	.byte $19,$83,$1a,$85,$19,$81,$17,$81,$14,$81
	.byte $ff,$19
	.word @ref1
	.byte $ff,$15
	.word @ref2
	.byte $ff,$19
	.word @ref3
	.byte $ff,$0c
	.word @ref4
	.byte $ff,$08
	.word @ref5
@ref14:
	.byte $1f,$83,$1d,$83,$26,$8d,$21,$91,$1f,$85,$1d,$85
@ref15:
	.byte $22,$83,$20,$83,$29,$8d,$24,$85,$22,$85,$2e,$87,$30,$87
@ref16:
	.byte $79,$94,$2e,$29,$28,$27,$26,$25,$24,$23,$22,$81,$1d,$81,$1e,$81
	.byte $1c,$81,$1d,$81,$19,$81,$1b,$81,$17,$81,$18,$81,$15,$81,$16,$81
	.byte $11,$81
@ref17:
	.byte $2e,$29,$28,$27,$26,$25,$24,$23,$22,$81,$1d,$81,$1e,$81,$1c,$a1
@ref18:
	.byte $7a,$88,$1b,$8d,$7b,$19,$8d,$7c,$18,$8d,$7d,$16,$8d
@ref19:
	.byte $7e,$16,$89,$76,$94,$22,$24,$25,$27,$29,$27,$25,$24,$22,$24,$25
	.byte $27,$29,$2a,$2c,$2e,$30,$31,$33,$32,$33,$34,$35,$34,$35,$81
@ref20:
	.byte $7f,$88,$1b,$8d,$19,$8d,$18,$8d,$16,$8d
@ref21:
	.byte $16,$89,$76,$94,$22,$24,$25,$27,$29,$27,$25,$24,$22,$24,$25,$27
	.byte $29,$2a,$2c,$2e,$30,$31,$33,$32,$33,$34,$35,$34,$35,$81
@ref22:
	.byte $7f,$88,$16,$9d,$7a,$15,$8d,$75,$8a,$29,$27,$76,$25,$24,$77,$25
	.byte $24,$78,$22,$20
@ref23:
	.byte $88,$22,$85,$79,$94,$20,$22,$23,$25,$27,$25,$23,$22,$20,$22,$23
	.byte $25,$27,$25,$27,$28,$2a,$28,$2a,$2c,$2e,$2c,$2e,$2f,$31,$33,$31
	.byte $34
@ref24:
	.byte $8a,$14,$95
@ref25:
	.byte $87,$7f,$0f,$8d
	.byte $fd
	.word @song0ch0loop

; RPGBattleTheme - Ted Kerr
@song0ch1:
@song0ch1loop:
@ref26:
	.byte $73,$86,$25,$28,$25,$28,$25,$28,$25,$28,$25,$28,$25,$28,$25,$28
	.byte $25,$28,$25,$2c,$25,$2c,$25,$2c,$25,$2c,$25,$2c,$25,$2c,$25,$2c
	.byte $25,$2c
@ref27:
	.byte $26,$2a,$26,$2a,$26,$2a,$26,$2a,$26,$2a,$26,$2a,$26,$2a,$26,$2a
	.byte $73,$88,$1d,$1e,$1f,$20,$1f,$1e,$1d,$1c,$1a,$1b,$1c,$1d,$1c,$1b
	.byte $1a,$81
	.byte $ff,$20
	.word @ref26
	.byte $ff,$20
	.word @ref27
@ref30:
	.byte $79,$18,$83,$1f,$83,$1f,$85,$73,$86,$24,$13,$18,$1f,$24,$13,$26
	.byte $21,$26,$28,$2a,$28,$2a,$2b,$2d,$2b,$2d,$2f,$31,$2f,$31,$32
@ref31:
	.byte $7c,$88,$13,$83,$17,$87,$23,$8d,$72,$86,$26,$21,$1e,$21,$26,$21
	.byte $26,$28,$2a,$28,$2a,$2b,$2d,$2b,$2d,$2f
@ref32:
	.byte $74,$22,$1b,$19,$1b,$22,$1b,$7a,$88,$26,$85,$74,$86,$19,$1b,$18
	.byte $1b,$19,$1b,$19,$1b,$19,$17,$19,$1b,$7a,$88,$19,$85,$74,$86,$19
	.byte $16,$19,$1b,$19,$16
@ref33:
	.byte $14,$19,$16,$14,$12,$19,$16,$14,$11,$19,$16,$14,$10,$19,$16,$14
	.byte $14,$17,$16,$14,$14,$17,$16,$14,$14,$17,$16,$14,$14,$17,$16,$14
@ref34:
	.byte $73,$25,$28,$25,$28,$25,$28,$25,$28,$25,$28,$25,$28,$25,$28,$25
	.byte $28,$25,$2c,$25,$2c,$25,$2c,$25,$2c,$25,$2c,$25,$2c,$25,$2c,$25
	.byte $2c
	.byte $ff,$20
	.word @ref27
	.byte $ff,$20
	.word @ref26
	.byte $ff,$20
	.word @ref27
	.byte $ff,$1c
	.word @ref30
	.byte $ff,$16
	.word @ref31
@ref40:
	.byte $78,$88,$16,$83,$1a,$83,$1f,$85,$72,$86,$35,$30,$35,$30,$78,$88
	.byte $1d,$87,$72,$86,$35,$2e,$35,$2e,$35,$2e,$37,$2e,$37,$2e,$37,$2e
	.byte $37
@ref41:
	.byte $78,$88,$1f,$83,$1d,$83,$22,$85,$72,$86,$30,$37,$30,$37,$78,$88
	.byte $20,$85,$1f,$85,$1f,$81,$74,$86,$38,$3a,$38,$3a,$75,$3c,$38,$3c
	.byte $38
@ref42:
	.byte $00,$81,$74,$94,$2e,$29,$28,$27,$26,$25,$24,$23,$22,$81,$72,$83
	.byte $86,$31,$2e,$31,$2e,$31,$2e,$7f,$8c,$22,$81,$24,$81,$7f,$25,$81
	.byte $27,$81,$25,$81,$24,$81
@ref43:
	.byte $22,$81,$76,$94,$2e,$29,$28,$27,$26,$25,$24,$23,$22,$81,$72,$86
	.byte $31,$2e,$31,$2e,$9f
@ref44:
	.byte $7a,$88,$19,$8d,$7b,$16,$8d,$7c,$15,$8d,$7d,$14,$8b,$00
@ref45:
	.byte $7e,$87,$79,$94,$22,$24,$25,$27,$29,$27,$25,$24,$22,$24,$25,$27
	.byte $29,$2a,$2c,$2e,$30,$31,$33,$32,$33,$34,$35,$34,$35,$81,$36,$81
@ref46:
	.byte $79,$35,$85,$62,$81,$7a,$81,$79,$81,$74,$81,$7a,$88,$16,$8d,$7f
	.byte $60,$15,$8d,$14,$8b,$00
@ref47:
	.byte $87,$79,$94,$22,$24,$25,$27,$29,$27,$25,$24,$22,$24,$25,$27,$29
	.byte $2a,$2c,$2e,$30,$31,$33,$32,$33,$34,$35,$34,$35,$81,$36,$81
@ref48:
	.byte $79,$35,$85,$62,$87,$77,$8f,$76,$8f,$75,$8a,$14,$16,$76,$17,$19
	.byte $77,$17,$19,$78,$1b,$1c
@ref49:
	.byte $7a,$60,$88,$23,$9d,$7a,$25,$9d
@ref50:
	.byte $7c,$94,$33,$81,$62,$83,$77,$8f
@ref51:
	.byte $74,$85,$5f,$81,$7f,$60,$8a,$1c,$8d
	.byte $fd
	.word @song0ch1loop

; RPGBattleTheme - Ted Kerr
@song0ch2:
@song0ch2loop:
@ref52:
	.byte $82,$19,$81,$20,$81,$19,$81,$20,$81,$19,$81,$20,$81,$19,$81,$20
	.byte $81,$19,$81,$20,$81,$19,$81,$20,$81,$19,$81,$20,$81,$19,$81,$20
	.byte $81
@ref53:
	.byte $1a,$81,$21,$81,$1a,$81,$21,$81,$1a,$81,$21,$81,$1a,$81,$21,$81
	.byte $16,$81,$1e,$81,$16,$81,$1e,$81,$17,$81,$23,$81,$18,$81,$24,$81
@ref54:
	.byte $19,$81,$20,$81,$19,$81,$20,$81,$19,$81,$20,$81,$19,$81,$20,$81
	.byte $19,$81,$20,$81,$19,$81,$20,$81,$19,$81,$20,$81,$19,$81,$20,$81
	.byte $ff,$20
	.word @ref53
@ref56:
	.byte $1f,$81,$18,$81,$1f,$81,$18,$81,$1f,$81,$18,$81,$1f,$81,$18,$81
	.byte $21,$81,$1a,$81,$21,$81,$1a,$81,$21,$81,$1a,$81,$21,$81,$1a,$81
	.byte $ff,$20
	.word @ref56
@ref58:
	.byte $16,$81,$0f,$81,$16,$81,$0f,$81,$18,$81,$11,$81,$18,$81,$11,$81
	.byte $19,$81,$14,$81,$19,$81,$14,$81,$1b,$81,$14,$81,$1b,$81,$14,$81
@ref59:
	.byte $22,$81,$16,$81,$22,$81,$16,$81,$1b,$81,$16,$81,$1b,$81,$16,$81
	.byte $1b,$81,$14,$81,$1b,$81,$14,$81,$1e,$81,$14,$81,$1e,$81,$14,$81
	.byte $ff,$20
	.word @ref54
	.byte $ff,$20
	.word @ref53
	.byte $ff,$20
	.word @ref54
	.byte $ff,$20
	.word @ref53
	.byte $ff,$20
	.word @ref56
	.byte $ff,$20
	.word @ref56
@ref66:
	.byte $16,$81,$0f,$81,$16,$81,$0f,$81,$16,$81,$0f,$81,$16,$81,$0f,$81
	.byte $18,$81,$11,$81,$18,$81,$11,$81,$18,$81,$11,$81,$18,$81,$11,$81
@ref67:
	.byte $19,$81,$12,$81,$19,$81,$12,$81,$19,$81,$12,$81,$19,$81,$12,$81
	.byte $1b,$81,$14,$81,$1b,$81,$14,$81,$1d,$81,$14,$81,$1d,$81,$14,$81
@ref68:
	.byte $16,$81,$0a,$81,$16,$81,$0a,$81,$16,$81,$0a,$81,$16,$81,$0a,$81
	.byte $16,$81,$0a,$81,$16,$81,$0a,$81,$16,$81,$0a,$81,$16,$81,$0a,$81
	.byte $ff,$20
	.word @ref68
	.byte $ff,$20
	.word @ref68
	.byte $ff,$20
	.word @ref68
	.byte $ff,$20
	.word @ref68
@ref73:
	.byte $1e,$81,$12,$81,$1e,$81,$12,$81,$1e,$81,$12,$81,$1e,$81,$12,$81
	.byte $1e,$81,$12,$81,$1e,$81,$12,$81,$1e,$81,$12,$81,$1e,$81,$12,$81
@ref74:
	.byte $1d,$81,$11,$81,$1d,$81,$11,$81,$1d,$81,$11,$81,$1d,$81,$11,$81
	.byte $1d,$81,$11,$81,$1d,$81,$11,$81,$1d,$81,$11,$81,$1d,$81,$11,$81
@ref75:
	.byte $1c,$81,$10,$81,$1c,$81,$10,$81,$1c,$81,$10,$81,$1c,$81,$10,$81
	.byte $1c,$81,$10,$81,$1c,$81,$10,$81,$1c,$81,$10,$81,$1c,$81,$10,$81
@ref76:
	.byte $1b,$81,$0f,$81,$1b,$81,$0f,$81,$1b,$81,$0f,$81
@ref77:
	.byte $1b,$81,$0f,$81,$20,$81,$14,$81,$20,$81,$14,$81
	.byte $fd
	.word @song0ch2loop

; RPGBattleTheme - Ted Kerr
@song0ch3:
@song0ch3loop:
@ref78:
	.byte $79,$84,$0c,$75,$0c,$73,$0c,$0c,$79,$07,$75,$0c,$74,$0c,$75,$0c
	.byte $74,$0c,$0c,$0c,$0c,$79,$07,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c
	.byte $0c,$79,$0c,$75,$0c,$0c,$0c,$79,$07,$75,$0c,$0c,$0c,$79,$07,$75
	.byte $0c,$0c,$0c
@ref79:
	.byte $79,$0c,$75,$0c,$73,$0c,$0c,$79,$07,$75,$0c,$79,$0c,$79,$0c,$75
	.byte $0c,$0c,$0c,$0c,$79,$07,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c
	.byte $79,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c
	.byte $0c,$0c
@ref80:
	.byte $79,$0c,$75,$0c,$73,$0c,$0c,$79,$07,$75,$0c,$74,$0c,$75,$0c,$74
	.byte $0c,$0c,$0c,$0c,$79,$07,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c
	.byte $79,$0c,$75,$0c,$0c,$0c,$79,$07,$75,$0c,$0c,$0c,$79,$07,$75,$0c
	.byte $0c,$0c
	.byte $ff,$20
	.word @ref79
	.byte $ff,$20
	.word @ref80
	.byte $ff,$20
	.word @ref79
	.byte $ff,$20
	.word @ref80
	.byte $ff,$20
	.word @ref79
	.byte $ff,$20
	.word @ref80
	.byte $ff,$20
	.word @ref79
	.byte $ff,$20
	.word @ref80
	.byte $ff,$20
	.word @ref79
	.byte $ff,$20
	.word @ref80
	.byte $ff,$20
	.word @ref79
@ref92:
	.byte $79,$0c,$75,$0c,$73,$0c,$0c,$79,$07,$75,$0c,$79,$0c,$75,$0c,$73
	.byte $0c,$0c,$0c,$0c,$79,$07,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c
	.byte $79,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c
	.byte $0c,$0c
@ref93:
	.byte $79,$0c,$75,$0c,$73,$0c,$0c,$79,$07,$75,$0c,$79,$0c,$75,$0c,$73
	.byte $0c,$0c,$0c,$0c,$79,$07,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$73,$0c
	.byte $0c,$79,$07,$75,$0c,$79,$0c,$75,$0c,$70,$90,$0e,$72,$0e,$73,$0e
	.byte $75,$0e,$78,$0e,$7a,$0e,$7c,$0e,$7f,$0e
@ref94:
	.byte $92,$01,$85,$79,$10,$81,$73,$84,$0c,$0c,$73,$0c,$0c,$0c,$0c,$79
	.byte $07,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c
	.byte $0c,$79,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c
@ref95:
	.byte $79,$0c,$75,$0c,$73,$0c,$0c,$79,$07,$75,$0c,$79,$0c,$75,$0c,$73
	.byte $0c,$0c,$0c,$79,$0c,$79,$07,$75,$0c,$0c,$0c,$7f,$0c,$77,$0c,$0c
	.byte $0c,$7f,$0c,$77,$0c,$0c,$0c,$7f,$0c,$77,$0c,$0c,$0c,$7f,$0c,$77
	.byte $0c,$0c,$0c
@ref96:
	.byte $79,$0c,$75,$0c,$73,$0c,$0c,$79,$07,$75,$0c,$79,$0c,$75,$0c,$73
	.byte $0c,$0c,$0c,$0c,$79,$07,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c
	.byte $79,$0c,$75,$0c,$0c,$0c,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c
	.byte $0c
@ref97:
	.byte $92,$01,$85,$75,$10,$81,$73,$84,$07,$73,$0c,$75,$0c,$0c,$0c,$0c
	.byte $79,$07,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c
	.byte $0c,$0c,$79,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c
	.byte $ff,$20
	.word @ref96
	.byte $ff,$1e
	.word @ref97
	.byte $ff,$20
	.word @ref80
	.byte $ff,$20
	.word @ref79
	.byte $ff,$0c
	.word @ref92
@ref103:
	.byte $79,$07,$75,$0c,$0c,$0c,$79,$0c,$75,$0c,$0c,$0c,$79,$0c,$75,$0c
	.byte $0c,$0c
	.byte $fd
	.word @song0ch3loop

; RPGBattleTheme - Ted Kerr
@song0ch4:
@song0ch4loop:
@ref104:
	.byte $81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81
	.byte $81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$20
	.word @ref104
	.byte $ff,$0c
	.word @ref104
	.byte $ff,$0c
	.word @ref104
	.byte $fd
	.word @song0ch4loop


; victoryloop - Ted Kerr
@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref130:
	.byte $8e,$20,$9d,$21,$9d
@ref131:
	.byte $23,$9d,$21,$9d
@ref132:
	.byte $20,$9d,$21,$9d
@ref133:
	.byte $23,$9d,$21,$9d
@ref134:
	.byte $1a,$1c,$1c,$89,$1a,$1c,$1c,$89,$20,$81,$21,$81,$23,$81,$26,$91
@ref135:
	.byte $28,$81,$26,$81,$23,$81,$23,$26,$23,$81,$21,$81,$20,$81,$1e,$81
	.byte $1a,$81,$1c,$81,$1c,$81,$1a,$91
	.byte $ff,$10
	.word @ref134
	.byte $ff,$18
	.word @ref135
@ref138:
	.byte $98,$1e,$89,$1a,$89,$28,$85,$26,$85,$1e,$95
@ref139:
	.byte $1e,$1f,$1e,$1f,$1e,$95,$1a,$1c,$1a,$1c,$1a,$95
@ref140:
	.byte $1c,$89,$1e,$89,$1a,$85,$18,$1a,$8b,$28,$26,$8b
@ref141:
	.byte $2b,$83,$2d,$83,$2b,$81,$2a,$85,$28,$85,$2a,$9d
	.byte $ff,$04
	.word @ref130
@ref143:
	.byte $23,$9d,$21,$9d
@ref144:
	.byte $20,$9d,$21,$9d
@ref145:
	.byte $23,$9d,$21,$9d
	.byte $ff,$0a
	.word @ref138
	.byte $ff,$0c
	.word @ref139
	.byte $ff,$0c
	.word @ref140
	.byte $ff,$0c
	.word @ref141
	.byte $fd
	.word @song1ch0loop

; victoryloop - Ted Kerr
@song1ch1:
@song1ch1loop:
@ref150:
	.byte $8e,$1c,$9d,$1c,$9d
@ref151:
	.byte $1c,$9d,$1c,$9d
@ref152:
	.byte $1c,$9d,$1c,$9d
@ref153:
	.byte $1c,$9d,$1c,$9d
	.byte $ff,$10
	.word @ref134
	.byte $ff,$18
	.word @ref135
	.byte $ff,$10
	.word @ref134
	.byte $ff,$18
	.word @ref135
@ref158:
	.byte $79,$98,$21,$89,$23,$89,$24,$85,$21,$85,$21,$95
@ref159:
	.byte $21,$23,$21,$23,$21,$95,$1e,$1f,$1e,$1f,$1e,$95
@ref160:
	.byte $1f,$89,$21,$89,$2a,$85,$28,$2a,$8b,$2b,$2a,$8b
@ref161:
	.byte $2f,$83,$2a,$83,$2f,$81,$2d,$8d,$26,$9d
@ref162:
	.byte $77,$1c,$17,$14,$17,$1c,$17,$14,$17,$1c,$17,$14,$17,$1c,$17,$14
	.byte $17,$1c,$17,$15,$17,$1c,$17,$15,$17,$1c,$17,$15,$17,$1c,$17,$15
	.byte $17
@ref163:
	.byte $1c,$17,$14,$17,$1c,$17,$14,$17,$1c,$17,$14,$17,$1c,$17,$14,$17
	.byte $1a,$17,$15,$17,$1a,$17,$15,$17,$1a,$17,$15,$17,$1a,$17,$15,$17
	.byte $ff,$20
	.word @ref162
	.byte $ff,$20
	.word @ref163
@ref166:
	.byte $79,$21,$89,$23,$89,$24,$85,$21,$85,$21,$95
	.byte $ff,$0c
	.word @ref159
	.byte $ff,$0c
	.word @ref160
	.byte $ff,$0a
	.word @ref161
	.byte $fd
	.word @song1ch1loop

; victoryloop - Ted Kerr
@song1ch2:
@song1ch2loop:
@ref170:
	.byte $80,$1c,$83,$1c,$28,$81,$26,$81,$23,$81,$1c,$81,$1c,$81,$1a,$17
	.byte $1c,$83,$1c,$28,$81,$26,$81,$23,$81,$1c,$81,$1c,$81,$1a,$17
@ref171:
	.byte $1c,$83,$1c,$28,$81,$26,$81,$23,$81,$1c,$81,$1c,$81,$1a,$17,$1c
	.byte $83,$1c,$28,$81,$26,$81,$23,$81,$1c,$81,$1c,$81,$1a,$17
	.byte $ff,$1e
	.word @ref171
	.byte $ff,$1e
	.word @ref171
	.byte $ff,$1e
	.word @ref171
	.byte $ff,$1e
	.word @ref171
	.byte $ff,$1e
	.word @ref171
	.byte $ff,$1e
	.word @ref171
@ref178:
	.byte $1a,$83,$1a,$26,$81,$24,$81,$21,$81,$1a,$81,$1a,$81,$18,$15,$1a
	.byte $83,$1a,$26,$81,$24,$81,$21,$81,$1a,$81,$1a,$81,$18,$15
	.byte $ff,$1e
	.word @ref178
	.byte $ff,$1e
	.word @ref178
	.byte $ff,$1e
	.word @ref178
	.byte $ff,$1e
	.word @ref171
	.byte $ff,$1e
	.word @ref171
	.byte $ff,$1e
	.word @ref171
	.byte $ff,$1e
	.word @ref171
	.byte $ff,$1e
	.word @ref178
	.byte $ff,$1e
	.word @ref178
	.byte $ff,$1e
	.word @ref178
	.byte $ff,$1e
	.word @ref178
	.byte $fd
	.word @song1ch2loop

; victoryloop - Ted Kerr
@song1ch3:
@song1ch3loop:
@ref190:
	.byte $96,$01,$81,$0d,$0d,$06,$81,$0d,$0d,$01,$81,$0d,$0d,$06,$81,$0d
	.byte $0d,$01,$81,$0d,$0d,$06,$81,$0d,$0d,$01,$81,$0d,$0d,$06,$81,$0d
	.byte $0d
@ref191:
	.byte $01,$81,$0d,$0d,$06,$81,$0d,$0d,$01,$81,$0d,$0d,$06,$81,$0d,$0d
	.byte $01,$81,$0d,$0d,$06,$81,$0d,$0d,$01,$81,$0d,$0d,$06,$81,$0d,$0d
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $fd
	.word @song1ch3loop

; victoryloop - Ted Kerr
@song1ch4:
@song1ch4loop:
@ref210:
	.byte $bf
@ref211:
	.byte $bf
@ref212:
	.byte $bf
@ref213:
	.byte $bf
@ref214:
	.byte $bf
@ref215:
	.byte $bf
@ref216:
	.byte $bf
@ref217:
	.byte $bf
@ref218:
	.byte $bf
@ref219:
	.byte $bf
@ref220:
	.byte $bf
@ref221:
	.byte $bf
@ref222:
	.byte $bf
@ref223:
	.byte $bf
@ref224:
	.byte $bf
@ref225:
	.byte $bf
@ref226:
	.byte $bf
@ref227:
	.byte $bf
@ref228:
	.byte $bf
@ref229:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


; Cave - Ted Kerr
@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref230:
	.byte $9e,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$a9,$04,$81,$06
	.byte $81,$12,$81,$04,$81,$06,$81,$12,$a9
@ref231:
	.byte $04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81
	.byte $12,$81,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$81,$04,$81
	.byte $06,$81,$12,$81,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$81
	.byte $04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81
@ref232:
	.byte $04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$a9,$04,$81,$06,$81
	.byte $12,$81,$04,$81,$06,$81,$12,$a9
	.byte $ff,$40
	.word @ref231
	.byte $ff,$18
	.word @ref232
	.byte $ff,$18
	.word @ref232
@ref236:
	.byte $7a,$12,$78,$12,$7a,$15,$78,$15,$7a,$17,$78,$17,$7a,$12,$78,$12
	.byte $7a,$15,$78,$15,$7a,$17,$78,$17,$7a,$12,$78,$12,$7a,$15,$78,$15
	.byte $7a,$17,$78,$17,$7a,$12,$78,$12,$7a,$15,$78,$15,$7a,$17,$78,$17
	.byte $7a,$12,$78,$12,$7a,$15,$78,$15,$7a,$17,$78,$17,$7a,$12,$78,$12
	.byte $7a,$15,$78,$15,$7a,$17,$78,$17,$7a,$12,$78,$12,$7a,$15,$78,$15
	.byte $7a,$17,$78,$17,$7a,$12,$78,$12,$7a,$15,$78,$15,$7a,$17,$78,$17
	.byte $7a,$12,$78,$12,$7a,$15,$78,$15,$7a,$17,$78,$17,$7a,$12,$78,$12
	.byte $7a,$15,$78,$15,$7a,$17,$78,$17,$7a,$12,$78,$12,$7a,$15,$78,$15
	.byte $ff,$40
	.word @ref236
	.byte $ff,$40
	.word @ref236
	.byte $ff,$40
	.word @ref236
	.byte $fd
	.word @song2ch0loop

; Cave - Ted Kerr
@song2ch1:
@song2ch1loop:
@ref240:
	.byte $77,$81,$9e,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$a9,$04
	.byte $81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$a7
@ref241:
	.byte $77,$81,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$81,$04,$81
	.byte $06,$81,$12,$81,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$81
	.byte $04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81
	.byte $12,$81,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$81,$04,$81
	.byte $06
@ref242:
	.byte $77,$81,$04,$81,$06,$81,$12,$81,$04,$81,$06,$81,$12,$a9,$04,$81
	.byte $06,$81,$12,$81,$04,$81,$06,$81,$12,$a7
	.byte $ff,$40
	.word @ref241
	.byte $ff,$19
	.word @ref242
	.byte $ff,$19
	.word @ref242
@ref246:
	.byte $00,$bd,$72,$a0,$1a,$73,$19,$74,$1a,$75,$19,$76,$1a,$77,$19,$78
	.byte $1a,$79,$19,$7a,$1a,$7b,$19,$7c,$1a,$7d,$19,$7e,$1a,$7f,$19,$7e
	.byte $1a,$7d,$19,$7c,$1a,$7b,$19,$7a,$1a,$79,$19,$78,$1a,$77,$19,$76
	.byte $1a,$75,$19,$74,$1a,$73,$19,$72,$1a,$89
@ref247:
	.byte $9f,$72,$1e,$72,$1c,$74,$1e,$74,$1c,$76,$1e,$76,$1c,$78,$1e,$78
	.byte $1c,$7a,$1e,$7a,$1c,$7b,$1e,$7b,$1c,$7c,$1e,$7c,$1c,$7d,$1e,$7d
	.byte $1c,$7c,$1f,$7c,$1e,$7c,$1f,$7c,$1e,$7c,$1f,$7c,$1e,$7c,$1f,$7c
	.byte $1e,$7c,$1f,$7c,$1e,$7c,$1f,$7c,$1e,$7c,$1f,$7c,$1e,$7c,$1f,$7c
	.byte $1e,$7b,$1d,$7a,$1c,$7a,$1d,$79,$1c,$79,$1d,$78,$1c,$78,$1d,$77
	.byte $1c,$77,$1e,$76,$1c,$76,$1e,$75,$1c,$75,$1e,$74,$1c,$74,$1e,$1c
@ref248:
	.byte $00,$bd,$72,$1a,$73,$19,$74,$1a,$75,$19,$76,$1a,$77,$19,$78,$1a
	.byte $79,$19,$7a,$1a,$7b,$19,$7c,$1a,$7d,$19,$7e,$1a,$7f,$19,$7e,$1a
	.byte $7d,$19,$7c,$1a,$7b,$19,$7a,$1a,$79,$19,$78,$1a,$77,$19,$76,$1a
	.byte $75,$19,$74,$1a,$73,$19,$72,$1a,$89
	.byte $ff,$31
	.word @ref247
	.byte $fd
	.word @song2ch1loop

; Cave - Ted Kerr
@song2ch2:
@song2ch2loop:
@ref250:
	.byte $9a,$00,$f5,$9a,$1c,$00,$1c,$00
@ref251:
	.byte $1e,$9d,$20,$8b,$6e,$11,$81,$6f,$11,$8f,$19,$bd
@ref252:
	.byte $00,$f5,$1c,$00,$1c,$00
@ref253:
	.byte $1e,$9d,$20,$8b,$6e,$11,$81,$6f,$11,$8f,$25,$bd
@ref254:
	.byte $00,$f9,$83
@ref255:
	.byte $f7,$21,$00,$21,$00
@ref256:
	.byte $17,$f9,$83
@ref257:
	.byte $a0,$1e,$bd,$9a,$1f,$9d,$1d,$9d
@ref258:
	.byte $17,$f9,$83
	.byte $ff,$06
	.word @ref257
	.byte $fd
	.word @song2ch2loop

; Cave - Ted Kerr
@song2ch3:
@song2ch3loop:
@ref260:
	.byte $79,$9c,$02,$8d,$0b,$8d,$0b,$8d,$0b,$8d,$79,$02,$8d,$0b,$8d,$0b
	.byte $8d,$0b,$85,$08,$81,$08,$81
@ref261:
	.byte $79,$02,$8d,$0b,$8d,$0b,$8d,$0b,$8d,$79,$02,$8d,$0b,$8d,$0b,$8d
	.byte $0b,$85,$08,$81,$08,$81
	.byte $ff,$14
	.word @ref261
	.byte $ff,$14
	.word @ref261
	.byte $ff,$14
	.word @ref261
	.byte $ff,$14
	.word @ref261
	.byte $ff,$14
	.word @ref261
	.byte $ff,$14
	.word @ref261
	.byte $ff,$14
	.word @ref261
	.byte $ff,$14
	.word @ref261
	.byte $fd
	.word @song2ch3loop

; Cave - Ted Kerr
@song2ch4:
@song2ch4loop:
@ref270:
	.byte $f9,$85
@ref271:
	.byte $f9,$85
@ref272:
	.byte $f9,$85
@ref273:
	.byte $f9,$85
@ref274:
	.byte $f9,$85
@ref275:
	.byte $f9,$85
@ref276:
	.byte $f9,$85
@ref277:
	.byte $f9,$85
@ref278:
	.byte $f9,$85
@ref279:
	.byte $f9,$85
	.byte $fd
	.word @song2ch4loop
