;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0

@sfx_ntsc_0:
	.byte $80,$75,$81,$d5,$82,$00,$01,$80,$f9,$01,$80,$75,$81,$8e,$01,$80
	.byte $f9,$00
