;this file for FamiTone5.1 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


soundtrack_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Placeholder

@instruments:
	.word @env1,@env0,@env0,@env1

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$cf,$ce,$ce,$cd,$ca,$c8,$c0,$00,$07


; Placeholder
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$1c,$85,$1f,$85,$23,$85,$1c,$85,$1c,$85,$1f,$85,$23,$85,$1c
	.byte $85,$23,$85,$1f,$85,$23,$85,$1c,$85,$1c,$85,$21,$85,$1f,$85,$23
	.byte $85
	.byte $fd
	.word @song0ch0loop

; Placeholder
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

; Placeholder
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

; Placeholder
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

; Placeholder
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
